services:
  book:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./Book:/Book
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
